var $log = console;
var plate = document.getElementsByClassName("plateContainer")[0];
var mousedown = false;
var lines = [];
var prevNode;
var passedNodes = [];
var DrewLines = [];
var levelDefault = 1;
var LevelJson;
var mouse;
var draginig = false;
var UserTurns;
var LevelsTime = 0;